### ISSUE TITLE
Event 1 (SM64) Roadmap

### ISSUE THREAD

**Issue by zoton2** [esamarathon/esa-btrl-layouts#1]
**Dashboard:**
- [x] Host Management
  - [x] Button to clone player into host if needed
- [ ] Player Management
  - [ ] One click button to update personal best if they get one at the event

**Graphics:**
- [x] Single View
  - [x] Sponsor logos placement
- [x] Multi View
  - [x] Respect "selected player" as main player
  - [x] Display extra players in a convenient way
  - [x] Timer for main player
  - [x] Timers for other players
  - [x] Extra player information/statistics
  - [x] General information/statistics in bottom area
  - [x] Sponsor logos placement
- [x] Overview
  - [x] Timers for each player
  - [x] General extra information/statistics in bottom area
  - [x] Sponsor logos placement
- [x] *All*:
  - [x] Add AFK notice if player is so

**Extension:**
- [x] OBS WebSockets logic
  - [x] Modify captures
  - [x] Transitions based on currently visible scene
- [x] Add "best possible time" from LiveSplit
- [ ] RabbitMQ messages
  - [x] Sponsor Logos
    - [ ] Add viewercount
  - [ ] Fully completed runs, the number for that player (and timestamp, but this is normal in our RabbitMQ messages)
- [ ] Add simple Twitch API implementation for getting public channel stats
- [x] xkeys implementation
  - [x] Mirror the "Layout Control" dashboard panel

**General:**
- [x] Check host names fit on all layouts
- [x] Animated transition for scene changes
- [x] Statistics
  - [x] Store completed runs/attempts data from LiveSplit instances
  - [x] Find a way to display stats (etc.) for hosts
- [x] Sponsor logos logic
- [ ] Should the current WR be displayed anywhere?

**Unrelated To Bundle:**
- [x] Player Personal OBS Layout:
  - [x] Make camera take up at least 587x328
  - [x] Create LiveSplit layout that fits well (could be horizontal?)
    - [x] Include the completed amount of runs
  - [x] Must show sponsor logos, can be a static image; [see this example](https://cdn.discordapp.com/attachments/145600678042009600/671421366418800659/image0.png)
- [ ] If possible, split player OBS recordings when they reset/start runs
- [x] xkeys legend
